# Dependencies
markdown:            kramdown
#highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title/

# Setup
title:               "Blog-Title"
name:				         "Vishal Salgotra"
tagline:             "A blog about C++ and everything."
description:         "Detailed description of blog goes here."
url:                 http://blog.scottlowe.org
baseurl:             /
paginate:            10

# About/contact
author:
  name:              Vishal Salgotra
  url:               https://twitter.com/scott_lowe
  email:             scott.lowe@scottlowe.org
  github:            salgotrav
  twitter:           scott_lowe

# Custom vars
version:             1.0.0

# Exclude Ruby gem stuff
exclude:             ["vendor"]

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
